# A generic workflow to build and push a Docker image.
#
# See the docs: /docs/docker-build-push.md
#
# This is a reusable workflow. See: https://docs.github.com/en/actions/using-workflows/reusing-workflows
#
# Note re. action versioning:
# GitHub recommends pinning actions to a commit SHA. To get a newer version, update the SHA.
# Although we can reference a tag or branch, it is not recommended as the action may change without warning.

on:
  workflow_call:
    inputs:

      # build args
      dockerfile_path:
        type: string
        required: false
        default: "./Dockerfile"
      build_context:
        type: string
        required: false
        default: "./"
      image: # e.g. nginx/nginx or eu.gcp.io/gcp-project/service-name
        type: string
        required: true
      label_title: # a sensible human-readable name for the image, used as metadata
        type: string
        required: true
      label_vendor: # the company who created the image. should probably be "3AP" (the default).
        type: string
        required: false
        default: "3AP"
      use_buildx:
        type: boolean
        required: false
        default: false # TODO review changing to true
      cache:
        type: boolean
        required: false
        default: false
      cache_mode:
        type: string # valid values: 'min', 'max'
        required: false # default 'min' set by docker/build-push-action

      # push args
      registry_domain:
        type: string
        required: true
      push: # disable pushing the image. Runs this workflow's build steps without pushing, which allows it to be used to test docker builds correctly.
        type: boolean
        required: false
        default: true

      # other args
      checkout:
        type: boolean
        required: false
        default: true # make sure to run actions/checkout manually before this workflow, if set to false


jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:

      # Checking out the repo is required by some of the following steps.
      # (docker/build-push-action can work without checking out but not the way we use it; with the path context)
      # When the checkout action is run, it replaces any changes made to an existing checkout.
      # To support in-CI changes, we can disable this step, and rely on a prior checkout run.
      - name: 'Checkout'
        if: ${{ inputs.checkout }}
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8' # v3.1.0

      - name: 'Fetch Docker container meta'
        id: 'docker_meta'
        uses: 'docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea' # v4.1.1
        with:
          images: ${{ inputs.docker_image }}
          labels: |-
            org.opencontainers.image.title=${{ inputs.docker_image_label_title }}
            org.opencontainers.image.vendor=${{ inputs.docker_image_label_vendor }}
          # Docker labels can be used to add well-known metadata to an image
          # A default title will be generated by the action by using the repo name.
          # The default tile isn't very useful for monorepos, so we overwrite it (even in non-monorepos).
          tags: |-
            type=semver,pattern={{version}}
            type=edge,branch=${{ github.event.repository.default_branch }}
            type=ref,event=branch,branch=feature/**
            type=ref,event=branch,branch=bugfix/**
            type=sha,enable=true,prefix=git-sha-,format=short
          # add tags:
          # - semver tag on every semver git tag
          # - "edge" on commits to the default branch
          # - branch name of "feature/**" or "bugfix/**" branches
          # - the git SHA on every commit
          # N.B.: want a custom tag for another env? add it here

      # Sets up a buildx instance that docker/build-push-action may use
      # Auto-enabled if caching is used with cache=true.
      - name: 'Set up Docker Buildx'
        if: ${{ inputs.use_buildx || inputs.cache }}
        uses: 'docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226' # v3.0.0

      - name: 'Build and push Docker image'
        uses: 'docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5' # v3.2.0
        with:
          context: ${{ inputs.docker_build_context }} # actions/checkout is required if a value is set for docker/build-push-action.context
          file: ${{ inputs.dockerfile_path }}
          push: ${{ inputs.push }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: ${{ inputs.cache && 'type=gha' || '' }}
          cache-to: ${{ inputs.cache && format('type=gha,mode={0}', inputs.cache_mode) || '' }}
